INFO     UpdateContactInfo:Web_Utils.py:24 Clicked element: ('link text', 'Update Contact Info')
ERROR    UpdateContactInfo:Web_Utils.py:52 Error entering text for element ('id', 'customer.firstName'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:52 Error entering text for element ('id', 'customer.lastName'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:52 Error entering text for element ('id', 'customer.address.street'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:52 Error entering text for element ('id', 'customer.address.city'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:52 Error entering text for element ('id', 'customer.address.state'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:52 Error entering text for element ('id', 'customer.address.zipCode'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:52 Error entering text for element ('id', 'customer.phoneNumber'): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:33 Error clicking element ('xpath', "//input[@value='Update Profile']"): Message: 
Stacktrace:
#0 0x55c93721478a <unknown>
#1 0x55c936cb70a0 <unknown>
#2 0x55c936d089b0 <unknown>
#3 0x55c936d08ba1 <unknown>
#4 0x55c936d56ea4 <unknown>
#5 0x55c936d2e3cd <unknown>
#6 0x55c936d542a0 <unknown>
#7 0x55c936d2e173 <unknown>
#8 0x55c936cfad4b <unknown>
#9 0x55c936cfb9b1 <unknown>
#10 0x55c9371d993b <unknown>
#11 0x55c9371dd83a <unknown>
#12 0x55c9371c1692 <unknown>
#13 0x55c9371de3c4 <unknown>
#14 0x55c9371a64cf <unknown>
#15 0x55c937202568 <unknown>
#16 0x55c937202746 <unknown>
#17 0x55c9372135f6 <unknown>
#18 0x7f59d109caa4 <unknown>
#19 0x7f59d1129c3c <unknown>

ERROR    UpdateContactInfo:Web_Utils.py:75 Timeout: Element ('xpath', "//h1[normalize-space()='Profile Updated']") not visible.
INFO     UpdateContactInfo:Web_Utils.py:72 Element ('xpath', "//p[@class='error']") is now visible.
INFO     UpdateContactInfo:Web_Utils.py:91 Retrieved text from element ('xpath', "//p[@class='error']"): An internal error has occurred and has been logged.
ERROR    UpdateContactInfo:Update_Contact_Info.py:86 An internal error has occurred and has been logged.