{"name": "test_find_transaction_daterange", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.", "trace": "self = <tests.test_parabank.Test_Para_Bank object at 0x7f06e1d07ec0>\n\n    def test_find_transaction_daterange(self):\n        global transaction_id, transaction_amount\n        findtransactions = FindTransactions(self.driver)\n        transaction_date = datetime.now().strftime(\"%m-%d-%Y\")\n        transaction_daterange_2value_list = (transaction_date, transaction_date)\n>       findtransactions.find_transaction_in_multiple_ways(find_transaction_value=\"find_transaction_daterange\",transaction_values=transaction_daterange_2value_list)\n\ntests/test_parabank.py:142: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/Find_Transactions.py:55: in find_transaction_in_multiple_ways\n    self.verify_transaction_history_present()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.Find_Transactions.FindTransactions object at 0x7f06e1d0c170>\n\n    def verify_transaction_history_present(self):\n        self.transaction_id_text = None\n        self.transaction_amount_text = None\n        with allure.step(str(\"verify_transaction_history_present\").replace(\"_\", \" \")):\n            if self.wait_until_element_is_visible(self.find_transaction_table_id):\n                with allure.step(f\"Transaction Table\"):\n                    allure.attach(self.driver.get_screenshot_as_png(), name=f\"Transaction Table\",attachment_type=allure.attachment_type.PNG)\n                if self.wait_until_element_is_visible(self.funds_transfer):\n                    self.click_on_element(self.funds_transfer)\n                    with allure.step(f\"Transaction ID and Amount\"):\n                        allure.attach(self.driver.get_screenshot_as_png(), name=f\"Transaction ID and Amount\",attachment_type=allure.attachment_type.PNG)\n                    id_text = self.get_text_from_element(self.transaction_id_text_xpath)\n                    self.transaction_id_text = re.sub(r'[^\\d.]', '', id_text)\n                    amount_text = self.get_text_from_element(self.transaction_amount_text_xpath)\n                    self.transaction_amount_text = re.sub(r'[^\\d.]', '', amount_text)\n                    with allure.step(f\"Transaction ID: {self.transaction_id_text}\"):pass\n                    with allure.step(f\"Transaction Amount: {self.transaction_amount_text}\"): pass\n            elif self.wait_until_element_is_visible(self.find_transaction_error_xpath):\n                error_text = self.get_text_from_element(self.find_transaction_error_xpath)\n                self.logger.error(f\"{error_text}\")\n                with allure.step(f\"ERROR: {error_text}\"):\n                    allure.attach(self.driver.get_screenshot_as_png(), name=f\"{error_text}\",attachment_type=allure.attachment_type.PNG)\n>                   pytest.fail(f\"{error_text}\")\nE                   Failed: An internal error has occurred and has been logged.\n\npages/Find_Transactions.py:149: Failed"}, "steps": [{"name": "find transaction daterange", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 55, in find_transaction_in_multiple_ways\n    self.verify_transaction_history_present()\n  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "click on find transaction", "status": "passed", "steps": [{"name": "Clicked element: ('link text', 'Find Transactions')", "status": "passed", "start": 1746772324565, "stop": 1746772324565}], "start": 1746772324411, "stop": 1746772324565}, {"name": "enter transaction daterange between", "status": "passed", "steps": [{"name": "Entered text: 05-09-2025 in element ('id', 'fromDate')", "status": "passed", "start": 1746772324624, "stop": 1746772324624}], "start": 1746772324565, "stop": 1746772324624}, {"name": "enter transaction daterange to", "status": "passed", "steps": [{"name": "Entered text: 05-09-2025 in element ('id', 'toDate')", "status": "passed", "start": 1746772324680, "stop": 1746772324680}], "start": 1746772324624, "stop": 1746772324680}, {"name": "click on find transaction daterange btn", "status": "passed", "steps": [{"name": "Clicked element: ('id', 'findByDateRange')", "status": "passed", "start": 1746772324737, "stop": 1746772324737}], "start": 1746772324680, "stop": 1746772324737}, {"name": "verify transaction history present", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "ERROR: An internal error has occurred and has been logged.", "status": "failed", "statusDetails": {"message": "Failed: An internal error has occurred and has been logged.\n", "trace": "  File \"/home/runner/work/ParaBank/ParaBank/pages/Find_Transactions.py\", line 149, in verify_transaction_history_present\n    pytest.fail(f\"{error_text}\")\n  File \"/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/_pytest/outcomes.py\", line 178, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "attachments": [{"name": "An internal error has occurred and has been logged.", "source": "1e9f8831-68ce-4f24-befd-40fc8947e6f6-attachment.png", "type": "image/png"}], "start": 1746772334960, "stop": 1746772335058}], "start": 1746772324737, "stop": 1746772335058}, {"name": "click on find transaction", "status": "passed", "steps": [{"name": "Clicked element: ('link text', 'Find Transactions')", "status": "passed", "start": 1746772335218, "stop": 1746772335218}], "start": 1746772335058, "stop": 1746772335218}], "start": 1746772324411, "stop": 1746772335218}], "attachments": [{"name": "failed_test", "source": "cc678409-04e7-4a8e-8a76-178ed586cd65-attachment.png", "type": "image/png"}, {"name": "log", "source": "e599799e-a556-43c2-80e6-18fcdec5bfa3-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "9af989bd-71b9-4080-b99f-0bb6a89d34d3-attachment.txt", "type": "text/plain"}], "start": 1746772324411, "stop": 1746772335219, "uuid": "aed0c713-2ef0-4f5e-9577-1cf6c4814e06", "historyId": "a3d22e5c16f72050ccec578856028f68", "testCaseId": "a3d22e5c16f72050ccec578856028f68", "fullName": "tests.test_parabank.Test_Para_Bank#test_find_transaction_daterange", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_parabank"}, {"name": "subSuite", "value": "Test_Para_Bank"}, {"name": "host", "value": "fv-az2029-263"}, {"name": "thread", "value": "3435-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_parabank"}]}